---
- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
    - xl2tpd

- name: /etc/xl2tpd/xl2tpd.conf configuration
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart xl2tpd 

- name: /etc/ppp/xl2tpd-options configuration
  template:
    src: xl2tpd-options.j2
    dest: /etc/ppp/xl2tpd-options
    owner: root
    group: root
    mode: 0644
  notify: restart xl2tpd 

- name: /etc/ppp/chap-secrets configuration
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    owner: root
    group: root
    mode: 0600
  notify: restart xl2tpd 

- name: xl2tpd service
  service:
    name: xl2tpd
    state: started
